config/routes.rb
Fremote::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'remotes#index'

  resources :remotes, only: [:index, :new, :create,:show,:update, :edit]
  resources :users, only: [:show]

  get 'remotes/:id/stream' => 'streams#stream'
  get 'remotes/:id/ping' => 'remotes#ping'
  post 'remotes/:id/clear' => 'drawings#clear'
  post 'remotes/:id/write' => 'drawings#write'
  put 'remotes/:id/drawings' => 'drawings#update'
  get 'remotes/:id/read' => 'drawings#read'
  post 'remotes/:id/change' => 'remotes#change'
  get 'time' => 'remotes#time'
  put 'remotes/:id/control' => 'remotes#control'
  get 'how-it-works' => 'pages#how_it_works'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-of-use' => 'pages#terms_of_use'
  match 'sitemap.xml', to: 'pages#sitemap', via: [:get, :post, :patch, :put, :delete], :defaults => {:format => :xml}
  get 'remotes/:id/chromecast-receiver' => 'casts#show'
  get 'chromecast-receiver' => 'casts#show'

  resources :remotes do
    resource :playlist, only: [:update, :show, :create, :destroy]
    resource :chat, controller: 'chat', only: [:create, :update]
  end

  match "/404", to: "errors#404_not_found", via: [:get, :post, :patch, :put, :delete]
  match "/422", to: "errors#422_unprocessable_entity", via: [:get, :post, :patch, :put, :delete]
  match "/500", to: "errors#500_internal_server_error", via: [:get, :post, :patch, :put, :delete]

end

app/models/remote.rb
class Remote
  include Rails.application.routes.url_helpers
  include Mongoid::Document
  include Mongoid::Timestamps
  include RemotesHelper
  after_initialize :spawn_embeds, :generate_remote_id
  field :remote_id, type: String
  field :name, type: String, default: "Unnamed Remote"
  field :description, type: String, default: "No description."
  field :url, type: String
  field :status, type: Integer, default: -1
  field :start_at, type: Integer, default: 0
  field :admin_only, type: Boolean, default: false
  field :watchers, type: Array, default: []
  field :last_controlled_at, type: DateTime, default: Time.now.utc
  index({ remote_id: 1 }, { unique: true, name: "remote_id_index" })
  belongs_to :user, index: true
  embeds_one :playlist
  index "playlist._id" => 1
  embeds_one :drawing
  index "drawing._id" => 1
  embeds_one :authorization
  index "authorization._id" => 1
  embeds_one :member_list
  index "member_list._id" => 1
  validates_presence_of :status
  validates_presence_of :start_at
  validates_length_of :description, maximum: 5000
  validates_length_of :name, maximum: 60

  def to_param
    remote_id
  end

  def json
    json_object = {}
    json_object["remote_id"] = self.remote_id
    json_object["url"] = self.url
    list = []
    self.playlist.list.each do |element|
      list << element
    end
    json_object["playlist"] = { "list" => list, "selection" => self.playlist.selection }
    json_object.to_json
  end

  def populate(url)
    unless url == ""
      push_link_to_playlist(url)
    else
      return { message: "URL can't be blank", status: :alert, path: root_path }
    end
  end

  def self.make(user = nil)
    if user
      return user.remotes.new
    else
      return self.new
    end
  end

  def update(params)
    if params[:name] != nil && params[:name] != ''
      self.name = params[:name]
    end
    
    if params[:description] != nil && params[:description] != ''
      self.description = params[:description]
    end

    delete_members(params) if params[:delete]

    if params[:member]
      check_if_members(params)
      self.authorization.update_permissions(params)
    end

    self.save
  end

  def populate_with_options(params, user = nil)
    self.name = params[:name] unless params[:name] == '' || params[:name] == nil
    self.description = params[:description] unless params[:description] == '' || params[:description] == nil
    self.admin_only = to_boolean(params[:admin_only]) || false
    check_if_members(params)
    self.save
    return { message: "Congratulations!  Take control of your remote.", status: :notice, path: remote_path(self.remote_id) }
  end

  def control(params, remote_owner = nil)
    if self.admin_only == false || remote_owner

      self.status = params["status"] if params["status"]
      self.start_at = params["start_at"].to_i if params["start_at"]
      self.last_controlled_at = Time.now.utc
      if remote_owner == self.user && params.has_key?("remote") && params["remote"].has_key?("admin_only")
        self.admin_only = to_boolean(params["remote"]["admin_only"])
      end

      check_if_selection(params)
    end
  end

  def skip
    unless (self.playlist.playing + 1) > (self.playlist.list.count - 1)
      self.playlist.playing += 1 if self.playlist.playing
      self.playlist.selection += 1
      self.status = 1
    end
    self.start_at = 0
    self.playlist.votes = 0
    self.playlist.save
    self.save
    Notify.new("playlist_block:#{self.remote_id}", {"block" => true}.to_json)
    Notify.new("control:#{self.remote_id}", {'start_at' => self.start_at, 'status' => self.status, 'updated_at' => self.updated_at, 'dispatched_at' => Time.now, 'stream_url' => URI::encode(Media.link(self.playlist.list[self.playlist.playing]["url"])) })
    Notify.new("playlist_play:#{self.remote_id}", 'playing' => self.playlist.playing)
    Notify.new("playlist_votes:#{self.remote_id}", {"votes" => self.playlist.votes}.to_json)
    Notify.new("playlist_block:#{self.remote_id}", {"block" => false}.to_json)
  end

  def kind_of_user(user = nil)
    if user
      determine_user_type(user)
    else
      return 'guest'
    end
  end

  private
  def spawn_embeds
    self.playlist = Playlist.new if self.playlist == nil
    self.drawing = Drawing.new if self.drawing == nil
    self.authorization = Authorization.new if self.authorization == nil 
    self.member_list = MemberList.new if self.member_list == nil
  end

  def generate_remote_id
    self.remote_id = Digest::MD5.hexdigest(DateTime.now.to_s + DateTime.now.nsec.to_s).slice(0..9) if self.remote_id == nil
  end

  def push_link_to_playlist(url)
    new_media = Media.new(url)
    if new_media != nil
      self.playlist.list << new_media
      self.save
      return { message: "Congratulations!  Take control of your remote.", status: :notice, path: remote_path(self.remote_id) }
    else
      return { message: "The video URL you provided is invalid.  Try again using a valid YouTube, Vimeo, Veoh, Blip, or Soundcloud URL.", status: :alert, path: root_path }
    end
  end

  def check_if_selection(params)
    if params["playing"]
      self.playlist.playing = params["playing"].to_i
      self.playlist.votes = 0
      self.playlist.save
      self.start_at = 0
      self.status = 1
      self.save
      Notify.new("playlist_play:#{self.remote_id}", {'playing' => self.playlist.playing})
      Notify.new("playlist_votes:#{self.remote_id}", {"votes" => self.playlist.votes}.to_json)
      Notify.new("playlist_block:#{self.remote_id}", {"block" => false}.to_json)
    end

    if params.has_key?("selection")
      change_playlist_selection(params)
    elsif params["status"] == 0 || params["status"] == "0"
      change_status_if_zero(params)
    else
      self.save
      Notify.new("control:#{self.remote_id}", {'start_at' => self.start_at, 'status' => self.status, 'updated_at' => self.last_controlled_at, 'dispatched_at' => Time.now })
      Notify.new("playlist_votes:#{self.remote_id}", {"votes" => self.playlist.votes}.to_json)
      Notify.new("playlist_play:#{self.remote_id}", 'playing' => self.playlist.playing)
    end
  end

  def change_playlist_selection(params)
    Notify.new("playlist_block:#{self.remote_id}", {"block" => true, "add" => true}.to_json)
    self.playlist.selection = params["selection"].to_i
    self.start_at = 0
    self.status = 1
    self.save
    Notify.new("control:#{self.remote_id}", {'start_at' => self.start_at, 'status' => self.status, 'updated_at' => self.updated_at, 'dispatched_at' => Time.now, 'stream_url' => URI::encode(Media.link(self.playlist.list[self.playlist.selection]["url"])) })
    Notify.new("playlist_play:#{self.remote_id}", 'playing' => self.playlist.playing)
    Notify.new("playlist_votes:#{self.remote_id}", {"votes" => self.playlist.votes}.to_json)
    Notify.new("playlist_block:#{self.remote_id}", {"block" => false}.to_json)
  end

  def change_status_if_zero(params)
    unless ((self.playlist.selection + 1) > (self.playlist.list.count - 1))
      self.playlist.selection = (self.playlist.selection + 1)
      self.status = 1
      self.playlist.playing += 1
    end
    self.start_at = 0
    self.playlist.votes = 0
    self.playlist.save
    self.save
    Notify.new("control:#{self.remote_id}", {'start_at' => self.start_at, 'status' => self.status, 'updated_at' => self.updated_at, 'dispatched_at' => Time.now, 'stream_url' => URI::encode(Media.link(self.playlist.list[self.playlist.selection]["url"])) })
    Notify.new("playlist_votes:#{self.remote_id}", {"votes" => self.playlist.votes}.to_json)
    Notify.new("playlist_play:#{self.remote_id}", 'playing' => self.playlist.playing)
  end

  def check_if_members(params)
    if params[:member] != [''] && params[:member]
      params[:member].each do |member|
        check_if_member_exists(member)
      end
    end
  end

  def check_if_member_exists(member)
    new_member = User.find_by({name: member})
    if new_member
      self.member_list.members << new_member.id
      new_member.add_to_membership(self)
    end
  end

  def delete_members(params)
    params[:delete].each do |delete_name|
      member = User.find_by({name: delete_name})
      self.member_list.members.delete(member.id)
      member.delete_remote_from_user_memberships(self)
    end
  end

  def determine_user_type(user)
    if self.member_list.members.include? user.id
      return 'member'
    elsif self.user && self.user.id == user.id
      return 'owner'
    else
      return 'user'
    end
  end
end

app/controllers/concerns/remotes.rb
module Remotes
  def self.what_to_render(user = nil, guest_name = nil)
    unless user
      "guest" unless guest_name
    else
      "show"
    end
  end
end

app/controllers/remotes_controller.rb
class RemotesController < ApplicationController

  include RemotesHelper

	def index
		@remote = Remote.new
	end

	def new
    if current_user
  		@user = current_user
  		@remote = Remote.new
      redirect_to root_path unless @remote.authorization.is_authorized?("settings", @user)
    else
      redirect_to root_path
    end
	end

	def create
		@user = current_user if current_user
		@remote = Remote.make(@user)
    @remote.authorization.update_permissions(params) if @user
    if params[:video_url]
  		dispatch = @remote.populate(params[:video_url])
    else
      dispatch = @remote.populate_with_options(params, @user)
    end
    flash[dispatch[:status]] = dispatch[:message]
    redirect_to dispatch[:path]
	end

	def edit
		@user = current_user if current_user
		@remote = Remote.find_by({remote_id: params[:id]})
		@remote_owner = @user if @user == @remote.user
		@members = @remote.member_list.members
    render "permission_denied" unless @remote.authorization.is_authorized?("settings", @user)
	end

	def update
		@user = current_user if current_user
		@remote = Remote.find_by({remote_id: params[:id]})
    @remote.update(params) if @remote.authorization.is_authorized?("settings", @user)
    respond_to do |format|
      format.json { render json: {'remote' => @remote}.to_json }
      format.html { redirect_to remote_path(@remote) }
    end
	end

	def control
		@user = current_user if current_user
		@remote = Remote.find_by({remote_id: params[:id]})
    @remote_owner = @user if @user == @remote.user
    @remote.control(params, @remote_owner) if @remote.authorization.is_authorized?("control", @user)
    render nothing: true
	end

	def ping
		@remote = Remote.find_by({remote_id: params[:id]})
		@playlist = @remote.playlist
    result = {'start_at' => @remote.start_at, 'status' => @remote.status, 'updated_at' => @remote.last_controlled_at.to_s, 'dispatched_at' => Time.now, 'sender_id' => 'fremote_server', 'selection' => @playlist.selection, 'stream_url' => URI::encode(Media.link(@playlist.list[@playlist.selection]["url"])), 'playlist' => @playlist.list, 'watchers' => @remote.watchers, 'playing' => @playlist.playing }
    render json: result.to_json
	end
  
  def change
    @remote = Remote.find_by({remote_id: params[:id]})
    @votes_to_skip = @remote.watchers.length / 3
    @remote.playlist.votes += 1
    @remote.playlist.save
    @remote.save
    @votes_to_skip = 1 if @votes_to_skip == 0
    Notify.new("playlist_votes:#{@remote.remote_id}", {"votes" => @remote.playlist.votes}.to_json)
    @remote.skip if @remote.playlist.votes >= @votes_to_skip

    render nothing: true
  end

	def show
    @user = current_user if current_user
    @remote = Remote.find_by({remote_id: params[:id]})
    @remote_owner = @user if @user == @remote.user
    @remote_json = @remote.json
    @identifier = (Time.now.strftime('%Y%m%d%H%M%S%L%N') + rand(400).to_s).to_s
    @username = Chat.guest_display_name(@user, params[:guest_name])
    cookies[:username] = @username
    @playlist = Playlist.new
    @remote_name = @remote.name
    @remote_description = @remote.description
    @remote_votes = @remote.playlist.votes
    @guest_name = Object.new
    render Remotes.what_to_render(@user, params[:guest_name])
	end

	def time
		render json: {time: Time.now.utc.to_s}.to_json
	end
end

app/helpers/remotes_helper.rb
module RemotesHelper
  def to_boolean(str)
    if str.to_s.downcase == "true" || str.to_s.downcase == "1" || str.to_s.downcase == "yes"
      true
    elsif str.to_s.downcase == "false" || str.to_s.downcase == "0" || str.to_s.downcase == "no" || str == nil 
      false
    else
      nil
    end
  end

  def is_authorized?(remote, user = nil)
    if user == remote.user || remote.admin_only == false
      return true
    else
      return false
    end
  end

  def user_type(remote, user = nil)
    if user
      if remote.member_list.members.include? user.id
        return 'member'
      elsif remote.user
        return 'owner' if remote.user.id == user.id
        return 'user'
      else
        return 'user'
      end
    else
      return 'guest'
    end
  end

  def sanitized_name(user)
    user_name = user.name.split(' ')
    return user_name.join('+')
  end

  def remote_authorization_checkbox(remote, kind, permission)
    if remote.authorization[kind][permission] == "1"
      check_box_tag "#{kind}[#{permission}]", 1, "active"
    elsif remote.authorization[kind][permission] == "0"
      check_box_tag "#{kind}[#{permission}]", 1
    end
  end

  def return_user(member)
    User.find(member)
  end
end

app/views/remotes/_canvas.html.haml
.center
  %canvas#drawing-surface{height: "310", width: "630"}
  - if remote.authorization.is_authorized?("draw", user)
    %span.canvas-controls
      %button#clear.btn.btn-noborder.btn-canvas-controls Clear Screen
      %p stroke color: 
      %input#color{name: "linecolor", type: "text", value: "#FF0000", class: "pick-a-color"}/
      %p stroke width: 
      %input#line{max: "10", min: "1", name: "points", type: "range", value: "5"}/

app/views/remotes/_chat.html.haml
%ul#chat.list-group
  - if remote.authorization.is_authorized?("chat", @user)
    %li#chat_title.list-group-item
      = form_for :remote, :url => remote_chat_path(remote), remote: true do |f|
        .input-group.input-group-sm
          = hidden_field_tag :username, username
          = text_field_tag :chat_message, "", :class => 'form-control', placeholder: 'enter a chat message here...', html: {:autocomplete => "off"}
          %span.input-group-btn
            = submit_tag "Send", class: "btn btn-inline"
        #chat_character_limit 500 characters left
  %li#chat_messages.list-group-item
    %table#chat_table.table
      %tbody#chat_table_body
        %tr
          %td.small.grey-text{colspan: "2"}
            - if remote.authorization.is_authorized?("chat", @user)
              Welcome to Fremote chat.  
              - unless current_user
                If you would like a dedicated username for the chat, sign up for an account!
            - else
              = "Welcome to Fremote chat. You are a #{user_type(remote, @user)} of this remote, so you do not have permission to chat."
              You must be any of these to use the chat: 
              - remote.authorization.permissions_by_user_type('chat').each do |user_type, permitted|
                - if permitted
                  = "#{user_type} " 

app/views/remotes/_owner_controls.html.haml
- if current_user
  #owner_controls.panel.panel-success
    .video-heading
      %h3.panel-title Remote Owner Controls
    .video-body
      = form_for(remote, remote: true, :html => {:id => "owner_controls_form"}) do |f|
        .checkbox
          %label
            Owner-only Controls #{f.check_box :admin_only}

app/views/remotes/_playlist.html.haml
%ul#playlist_group.list-group.panel
  %li.list-group-item.video-heading
    %h3.panel-title Playlist
    - if remote.authorization.is_authorized?("playlist", current_user)
      %button.btn.btn-noborder.right#clear_playlist Clear Playlist
  - if remote.authorization.is_authorized?("playlist", current_user)
    %li.list-group-item
      = form_for :playlist, url: remote_playlist_path(remote.remote_id), remote: true, html: { id: "playlist_form" } do |f|
        .input-group.input-group-sm
          = hidden_field_tag :username, username
          = text_field_tag :url, "", :class => 'form-control', placeholder: 'add a url to the playlist here...', html: {:autocomplete => "off"}, id: "playlist_url_field"
          %span.input-group-btn
            = submit_tag "Add", class: "btn btn-inline"
  - else
    %p.small.grey-text.padding
      = "You are a #{user_type(remote, @user)} of this remote, so you do not have permission to add to this playlist."
      You must be any of these to use the playlist: 
      - remote.authorization.permissions_by_user_type('playlist').each do |user_type, permitted|
        - if permitted
          = "#{user_type} " 

  %li.list-group-item.video-body
    %ol#playlist.sortable.list

  :javascript
    var authorized = "#{remote.authorization.is_authorized?("playlist", current_user)}"

app/views/remotes/_playlist_info.html.haml
- meta :description => @remote.description
#video_info.panel
  .video-heading
    -if @remote.authorization.is_authorized?('settings', current_user)
      #remote_name
        %span.glyphicon.glyphicon-edit.left
        %h3.panel-title.inline= @remote.name
    - else
      %h3.panel-title= @remote.name
  .video-body
    %p
      %label
        Share URL: #{ text_field_tag :share, 'http://fremote.tv' + remote_path(@remote), spellcheck: "false" }
      -if @remote.authorization.is_authorized?('settings', current_user)
        = link_to 'Edit Remote', edit_remote_path(@remote.remote_id), class: "btn btn-noborder right"
    %span.right
      %span#skip.btn.btn-noborder
        Skip
        %span.glyphicon.glyphicon-fast-forward
      %span#votes_skip
        Votes: #{ @remote_votes }
    -if @remote.authorization.is_authorized?('settings', current_user)
      #remote_description
        %span.glyphicon.glyphicon-edit.left
        %p.inline= @remote.description
    - else
      %p= @remote.description

app/views/remotes/_video.html.haml
.alert.alert-danger.connect-alert
  %dialog#flash_alert Attempting to connect...
%video#player.video-js.vjs-default-skin.center{controls: "", "data-setup" => '{"techOrder": ["html5","ChromecastTech","flash"]}', preload: "auto", height: "355", width: "630"}

app/views/remotes/_watchers.html.haml
%ul#watchers_group.list-group.panel
  %li.list-group-item.video-heading
    %h3.panel-title
      Users currently watching this remote:
  %li.list-group-item.video-body
    #watchers_key.right
      - if @remote.user
        %span.glyphicon.glyphicon-star.owner
        %span Owner
        %span.glyphicon.glyphicon-user.member
        %span Member
    %ul#watchers.list

app/views/remotes/edit.html.haml
- content_for(:title){ "Edit Remote - Fremote" }
.container
  #remote
    %h3 Edit Remote
    = form_for @remote, :url => { :controller => 'remotes', :action => 'update' }, :html => {:id => "edit_remote"} do |f|
      .input-group.full-width
        = text_field_tag :name, @remote.name, :class => 'form-control', placeholder: 'Optional: Name your remote here...'
        = text_area_tag :description, @remote.description, :class => 'form-control', placeholder: 'Optional: Describe your remote here...'
      - if @remote.user
        %table.table.table-responsive
          %thead
            %tr
              %td
              %td
                Controls
              %td
                Playlist Edit
              %td
                Chat
              %td
                Draw
              %td
                Settings
          %tbody
            %tr
              %td
                Guest
              %td
                = remote_authorization_checkbox(@remote, "_guest", "control")
              %td
                = remote_authorization_checkbox(@remote, "_guest", "playlist")
              %td
                = remote_authorization_checkbox(@remote, "_guest", "chat")
              %td
                = remote_authorization_checkbox(@remote, "_guest", "draw")
              %td
                = remote_authorization_checkbox(@remote, "_guest", "settings")
            %tr
              %td
                User
              %td
                = remote_authorization_checkbox(@remote, "_user", "control")
              %td
                = remote_authorization_checkbox(@remote, "_user", "playlist")
              %td
                = remote_authorization_checkbox(@remote, "_user", "chat")
              %td
                = remote_authorization_checkbox(@remote, "_user", "draw")
              %td
                = remote_authorization_checkbox(@remote, "_user", "settings")
            %tr
              %td
                Member
              %td
                = remote_authorization_checkbox(@remote, "_member", "control")
              %td
                = remote_authorization_checkbox(@remote, "_member", "playlist")
              %td
                = remote_authorization_checkbox(@remote, "_member", "chat")
              %td
                = remote_authorization_checkbox(@remote, "_member", "draw")
              %td
                = remote_authorization_checkbox(@remote, "_member", "settings")
        .input-group.full-width
          = text_field_tag 'member[]', '', :class => 'form-control', placeholder: 'Optional: add other members to the remote'
          %span#add_members.glyphicon.glyphicon-plus
          - if @members
            %ul.padded#members.opacity.list-unstyled
              %li#added_members 
                Members to Add:
                %ul.inside-member-list
              %li 
                Current Members:
                %ul.inside-member-list
                  - unless @members == []
                    - @members.each do |member|
                      %li
                        = "#{return_user(member).name}"
                        - unless return_user(member) == current_user
                          %button.right.btn-xfs.btn-danger.user-delete X
                  - else
                    %li.list-unstyled There are no members assigned to this remote.

      .input-group
        %span.input-group-btn
          = submit_tag "Update Remote", class: "btn full-width"

  :javascript
    var remote_id = '#{@remote.remote_id}'

app/views/remotes/guest.html.haml
- content_for(:title){ "Enter Guest Name - Fremote" }
.col-xs-8.col-xs-offset-2
  %h3
    Before you can use this remote...
  %p
    \...you'll need a temporary guest name.  You can enter your own, but if you don't want to then we'll give you a nickname. ;)
  = form_for :guest_name, :url => remote_path(@remote), method: "get" do |f|
    .input-group.input-group-sm
      = text_field_tag :guest_name, "", :class => 'form-control', placeholder: 'put a temporary guest name here, if you want...', html: {:autocomplete => "off"}
      %span.input-group-btn
        = submit_tag "Use Remote", class: "btn btn-inline"

app/views/remotes/how_it_works.html.haml
.col-xs-6.col-xs-offset-3
  %h3
    What's this "Fremote" thing?
  %p
    With Fremote, you can create a remote to take control of your online videos.  This remote will let you play/pause/scrub the video for whoever is watching.  It's a great way to watch videos together with friends over the net.  Your remote also lets you create a playlist and chat with watchers.  
  %p
    You can make remotes without registering, but an account gives you a dedicated chat handle and extra remote settings. 
  %p
    All you need to get started is a YouTube, Vimeo, Blip, Veoh, or Soundcloud link.
  %p
    Keep in mind that you must have a fast internet connection for a good Fremote experience.  We also suggest using a modern web browser that supports HTML5 video.  We like Google Chrome, Mozilla Firefox, and Internet Explorer 10+.
  = image_tag("ski_instructor.jpg", class: "img-responsive")
  %p
    &nbsp;
  %p
    Now that you know what this is all about...
  %p.text-align-center
    = link_to('Create a Remote!', root_path, html_options = {class: "btn btn-success"})

app/views/remotes/index.html.haml
#on_landing
	.container
		.tab-content
			#landing.tab-pane.active.fade.in
				%p.left create a remote
				= form_for :remote, :url => { :controller => 'remotes', :action => 'create' }, :html => {:id => "new_remote"} do |f|
					.input-group.full-width
						= hidden_field_tag "quick_remote", "true"
						= text_field_tag :video_url, "", :class => 'form-control', placeholder: 'enter a video url here...'
						%span.input-group-btn
							= submit_tag "Create Remote", class: "btn btn-inline"
				%p.right and watch videos together
	.col-sm-8.col-sm-offset-2.col-lg-6.col-lg-offset-3
		%p
			%h5.text-align-center.light-green-text
				We support videos from:
		= image_tag("providers.png", class: "img-responsive")
		%p.text-align-center
			%br
			%script{async: "", src: "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
			%ins.adsbygoogle{"data-ad-client" => "ca-pub-2416283885970714", "data-ad-slot" => "9719555789", style: "display:inline-block;width:468px;height:60px"}
			:javascript
				(adsbygoogle = window.adsbygoogle || []).push({});

app/views/remotes/new.html.haml
- content_for(:title){ "New Remote - Fremote" }
.container
  #remote
    %h3 New Remote    
    - if current_user  
      = form_for :remote, :url => { :controller => 'remotes', :action => 'create' }, :html => {:id => "new_remote"} do |f|
        .input-group.full-width
          = text_field_tag :name, '', :class => 'form-control', placeholder: 'Optional: Name your remote here...'
          = text_area_tag :description, '', :class => 'form-control', placeholder: 'Optional: Describe your remote here...'
        %table.table.table-responsive
          %thead
            %tr
              %td
              %td
                Controls
              %td
                Playlist
              %td
                Chat
              %td
                Draw
              %td
                Settings
          %tbody
            %tr
              %td
                Guest
              %td
                = check_box_tag '_guest[control]', 1
              %td
                = check_box_tag '_guest[playlist]', 1
              %td
                = check_box_tag '_guest[chat]', 1, 'active'
              %td
                = check_box_tag '_guest[draw]', 1
              %td
                = check_box_tag '_guest[settings]', 1
            %tr
              %td
                User
              %td
                = check_box_tag '_user[control]', 1
              %td
                = check_box_tag '_user[playlist]', 1
              %td
                = check_box_tag '_user[chat]', 1, 'active'
              %td
                = check_box_tag '_user[draw]', 1
              %td
                = check_box_tag '_user[settings]', 1
            %tr
              %td
                Member
              %td
                = check_box_tag '_member[control]', 1, 'active'
              %td
                = check_box_tag '_member[playlist]', 1, 'active'
              %td
                = check_box_tag '_member[chat]', 1, 'active'
              %td
                = check_box_tag '_member[draw]', 1, 'active'
              %td
                = check_box_tag '_member[settings]', 1
        .input-group.full-width
          = text_field_tag 'member[]', '', :class => 'form-control', placeholder: 'Optional: add other members to the remote'
          %span#add_members.glyphicon.glyphicon-plus
          %ul.padded#members.opacity.list-unstyled
            %li#added_members
              Members to Add:
              %ul.inside-member-list

        .input-group
          %span.input-group-btn
            = submit_tag "Create Remote", class: "btn full-width"

  :javascript
    var remote_id = '0'

app/views/remotes/show.html.haml
- content_for(:title){ "#{@remote.name} - Fremote" }
%div.text-align-center
  %script{async: "", src: "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
  %ins.adsbygoogle{"data-ad-client" => "ca-pub-2416283885970714", "data-ad-slot" => "3533421389", style: "display:inline-block;width:728px;height:90px"}
  :javascript
    (adsbygoogle = window.adsbygoogle || []).push({});
#show_remote
  .container
    .row.clearfix
      .col-md-12.column
        .row.clearfix
          .col-md-8.col-lg-7.column
            = render :partial => 'video', :locals => { :remote => @remote, :remote_user => @remote_user }
            = render :partial => 'canvas', :locals => { :remote => @remote, :user => @user }
          .col-md-4.col-lg-5.column
            = render :partial => 'chat', :locals => { :username => @username, :remote => @remote }
        .row.clearfix
          .col-md-8.col-lg-7.column
            = render :partial => 'playlist_info', :locals => { :remote => @remote, :remote_user => @remote_user }
          .col-md-4.col-lg-5.column#watchers_container
            = render :partial => 'watchers', :locals => { :remote => @remote }
        .row.clearfix
          .col-md-12.column
            = render :partial => 'playlist', :locals => { :remote => @remote, :username => @username }

  :javascript
    var user = '#{@identifier}'
    var remote_id = '#{@remote.remote_id}'