config/routes.rb
Fremote::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'remotes#index'

  resources :remotes, only: [:index, :new, :create,:show,:update, :edit]
  resources :users, only: [:show]

  get 'remotes/:id/stream' => 'streams#stream'
  get 'remotes/:id/ping' => 'remotes#ping'
  post 'remotes/:id/clear' => 'drawings#clear'
  post 'remotes/:id/write' => 'drawings#write'
  put 'remotes/:id/drawings' => 'drawings#update'
  get 'remotes/:id/read' => 'drawings#read'
  post 'remotes/:id/change' => 'remotes#change'
  get 'time' => 'remotes#time'
  put 'remotes/:id/control' => 'remotes#control'
  get 'how-it-works' => 'pages#how_it_works'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-of-use' => 'pages#terms_of_use'
  match 'sitemap.xml', to: 'pages#sitemap', via: [:get, :post, :patch, :put, :delete], :defaults => {:format => :xml}
  get 'remotes/:id/chromecast-receiver' => 'casts#show'
  get 'chromecast-receiver' => 'casts#show'

  resources :remotes do
    resource :playlist, only: [:update, :show, :create, :destroy]
    resource :chat, controller: 'chat', only: [:create, :update]
  end

  match "/404", to: "errors#404_not_found", via: [:get, :post, :patch, :put, :delete]
  match "/422", to: "errors#422_unprocessable_entity", via: [:get, :post, :patch, :put, :delete]
  match "/500", to: "errors#500_internal_server_error", via: [:get, :post, :patch, :put, :delete]

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :name, type: String
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  validates_length_of :name, maximum: 16
  validates :name, :exclusion => %w[sign_in sign_out sign_up password cancel edit]
  validate :disallow_nonalphanumerics
  # attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
  index({ name: 1 }, { unique: true, name: "name_index" })

  after_initialize :spawn_memberships
  has_many :remotes
  embeds_one :membership
  index "membership._id" => 1


  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      self.any_of({ :name => /^#{Regexp.escape(login)}$/i }, { :email => /^#{Regexp.escape(login)}$/i }).first
    else
      super
    end
  end

  def add_to_membership(remote)
    unless self.membership.remote_ids.include? remote.remote_id
      self.membership.remote_ids << remote.remote_id
      self.save
    end
  end

  def delete_remote_from_user_memberships(remote)
    self.membership.remote_ids.delete(remote.remote_id)
    self.save
  end

  private
  def spawn_memberships
    self.membership = Membership.new if self.membership == nil
  end

  def disallow_nonalphanumerics
    if name.match(/^[a-zA-Z0-9\-\_\s]+$/).nil?
      errors.add(:name, "can only include letters, numbers, dashes (-), and underscores (_)")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @unsanitized_username = params[:id].sub('+', ' ')

    @user_viewed = User.find_by({name: @unsanitized_username})
    @remotes = Remote.where({user: @user_viewed})
    
    @memberships = @user_viewed.membership.remote_ids
    @memberships.map! do |remote_id|
      Remote.find_by({remote_id: remote_id})
    end
  end
end

app/views/users/show.html.haml
.container
  #show_user
    %h3
      #{@user_viewed.name}
    .container
      .row.clearfix
        .col-md-12.column
          .row.clearfix
            .col-md-6.column
              %h4 Remotes
              - if @remotes != []
                - @remotes.each do |remote|
                  %ul.list-unstyled.list-border
                    %li
                      %h5
                        %span.glyphicon.glyphicon-link
                        = link_to "#{remote.name}", remote_path(remote.remote_id)
                      %ul.list-unstyled
                        %li.margin-left #{remote.description}
              - else
                %p This user has no remotes.
                
            .col-md-6.column
              %h4 Memberships
              - if @memberships != []
                - @memberships.each do |remote|
                  %ul.list-unstyled.list-border
                    %li
                      %h5
                        %span.glyphicon.glyphicon-link
                        = link_to "#{remote.name}", remote_path(remote.remote_id)
                      %ul
                        %li #{remote.description}   
              - else
                %p This user is not a member of any remotes.