config/routes.rb
Fremote::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'remotes#index'

  resources :remotes, only: [:index, :new, :create,:show,:update, :edit]
  resources :users, only: [:show]

  get 'remotes/:id/stream' => 'streams#stream'
  get 'remotes/:id/ping' => 'remotes#ping'
  post 'remotes/:id/clear' => 'drawings#clear'
  post 'remotes/:id/write' => 'drawings#write'
  put 'remotes/:id/drawings' => 'drawings#update'
  get 'remotes/:id/read' => 'drawings#read'
  post 'remotes/:id/change' => 'remotes#change'
  get 'time' => 'remotes#time'
  put 'remotes/:id/control' => 'remotes#control'
  get 'how-it-works' => 'pages#how_it_works'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-of-use' => 'pages#terms_of_use'
  match 'sitemap.xml', to: 'pages#sitemap', via: [:get, :post, :patch, :put, :delete], :defaults => {:format => :xml}
  get 'remotes/:id/chromecast-receiver' => 'casts#show'
  get 'chromecast-receiver' => 'casts#show'

  resources :remotes do
    resource :playlist, only: [:update, :show, :create, :destroy]
    resource :chat, controller: 'chat', only: [:create, :update]
  end

  match "/404", to: "errors#404_not_found", via: [:get, :post, :patch, :put, :delete]
  match "/422", to: "errors#422_unprocessable_entity", via: [:get, :post, :patch, :put, :delete]
  match "/500", to: "errors#500_internal_server_error", via: [:get, :post, :patch, :put, :delete]

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.haml
%nav#top_nav.navbar.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("logo.svg", class:"img-responsive"), root_path, class: 'navbar-brand', id: 'nav_logo'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left= render 'layouts/supplemental_links'
      %ul.nav.navbar-nav.navbar-right= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%p.navbar-text.pull-right
  - if user_signed_in?
    Welcome,
    = succeed "." do
      %strong= current_user.name
    = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
    |
    = link_to 'New remote', new_remote_path, :class => 'navbar-link'
    |
    = link_to 'View remotes and memberships', user_path(sanitized_name(current_user)), :class => 'navbar-link'
    |
    \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
  - else
    = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
    |
    \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}

app/views/layouts/_supplemental_links.html.haml
%p.navbar-text.pull-left.spaced-apart-links
  = link_to 'How it works', '/how-it-works', :class => 'navbar-link'
  = link_to 'Blog', 'http://paradoxsector.blogspot.com/', :class => 'navbar-link'

app/views/layouts/application.html.haml
!!!
%html{"data-cast-api-enabled" => "true"}
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Fremote"
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png'
    = metamagic :description => "Take control of your online videos.  Create remotes to watch videos together with others simultaneously.", :keywords => %w(video remote music audio movies share chat playlist simultaneous synchronous sync synchronized youtube vimeo blip soundcloud mp3 mp4 stream), :'revisit-after' => "1 days", :robots => "index, follow", :author => "ParadoxSector"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = javascript_pluggable_tag
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
  %body
    %header= render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
      = yield
      .spacer
    #footer.muted{style: "text-align: center;"}
      %p 
        Fremote © 2014 ParadoxSector  ·  #{link_to 'Privacy Policy', '/privacy-policy'}  ·  #{link_to 'Terms of Use', '/terms-of-use'} 